spring:
  application:
    name: E-Catalog
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: example
  sql:
    init:
      mode: never

management:
  endpoints:
    web:
      exposure:
        include: "*"


logging:
  level:
    net.barrage.school.java.ecatalog: DEBUG

ecatalog:
  products:
    sources:
      - name: Uncle
        format: json
        url: https://www.dropbox.com/scl/fi/mhq4vmv42x1hy5k430ae3/products.json?rlkey=00w6n2cfjk8p5wwizz6c4tckr&dl=1
      - name: John
        format: xml
        url: https://www.dropbox.com/scl/fi/yznlmzbqvu0itaysh6069/vina.xml?rlkey=l88zrfm60qbys1nj12p1u605r&dl=1
        remote: true
      - name: Bob
        format: xlsx
        url: https://www.dropbox.com/scl/fi/rxime4x4tvzxoqvts5g4d/vegetables.xlsx?rlkey=7mrjxnnuqrxygmmi79di5klgl&dl=1
