#Does this here work like .env in javascript?
#I see that we are using "${ecatalog.products.source-path}" in Implementation,
#so I'm wondering if that's the case here?

logging:
  level:
    net.barrage.school.java.ecatalog: DEBUG

ecatalog:
  products:
    source-path: src/main/resources/static/products.json
    sources:
      - name: Uncle
        url: https://www.dropbox.com/scl/fi/mhq4vmv42x1hy5k430ae3/products.json?rlkey=00w6n2cfjk8p5wwizz6c4tckr&dl=0
        format: json
      - name: Mirko
        url: https://www.dropbox.com/scl/fi/rxime4x4tvzxoqvts5g4d/vegetables.xlsx?rlkey=7mrjxnnuqrxygmmi79di5klgl&dl=0
        format: xlsx
      - name: Slavko
        url: https://www.dropbox.com/scl/fi/wbbsxcx6mh58iood031qo/wines.xml?rlkey=x7dmdsnv0gjvalskxwstlxjlr&dl=0
        format: xml

