# https://prometheus.io/docs/prometheus/latest/getting_started/
global:
  scrape_interval: 15s # By default, scrape targets every 15 seconds.

scrape_configs:
  - job_name: 'e-catalog'
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    static_configs:
      # Use 'host.docker.internal' as the alias to access the host machine on macOS
      - targets: [ 'host.docker.internal:8080' ]